### ISSUE TITLE
Default src

### ISSUE THREAD

**Issue by clonq** [guigrpa/storyboard#22]
is there a way to define a default namespace for a child story?

**Comment by guigrpa** [comment]
Do you mean something like this? I'm setting the story's source and title:

```
const story = mainStory.child({ src: 'database', title: 'Database request' });
```

**Comment by clonq** [comment]
Right, didn't realize src is actually the namespace. Thanks!

**Comment by clonq** [comment]
If i call log.debug with a single param i still get 'main' as the namespace/src. i was expecting the src specified in the .child call to propagate. It only works if you provide 2 params, the first one being the namespace/src. Is that by design?

**Comment by guigrpa** [comment]
Yes, that's in principle by design. The `src` attribute is the *source* of the log, e.g. which module it comes from. This is orthogonal to the *story*, which may be passed around by different modules, and even start in the client, passed to the server, and then back to the client, things like that.

It might be useful though, in some use cases, to define a default src for a story… Would you like to submit a PR for this?

**Comment by guigrpa** [comment]
Closed due to lack of activity
