### ISSUE TITLE
DevTools extensions for chrome mobile ?

### ISSUE THREAD

**Issue by Nic2012** [guigrpa/storyboard#5]
Storyboard is a great lib, thank y.
But is there any chance to trace the logs in a chrome browser on Android?
Or any other alternative?

Best regards,
Nic

**Comment by guigrpa** [comment]
Interesting idea! I've put up a proof-of-concept in branch [feature-uploadClientLogs](https://github.com/guigrpa/storyboard/tree/feature-uploadClientLogs). 

If you want to test it, download this branch and run:

```bash
$ npm install
$ npm run buildExample
$ npm run example
```

Then open the following URLs in your browser: 

* *Monitor*: [http://localhost:8090](http://localhost:8090)
* Example client application with upload: [http://localhost:3000/exampleUpload.html](http://localhost:3000/exampleUpload.html)

Now if you open the *Storyboard DevTools* on the monitor and log in (any credential is fine), you'll see the logs from the console-less application in the **Client** section. Every time you reload the client application (the second URL), you'll get a new top-level story in the DevTools. **Feedback is welcome!**

Screenshot:

![uploadedstories](https://cloud.githubusercontent.com/assets/2129481/14429100/4f2cbf2c-fffc-11e5-96d7-abbb8a3dcde3.png)

**Comment by guigrpa** [comment]
Something I forgot: logs and stories generated at the client(s) will not pollute the server's console.

**Comment by Nic2012** [comment]
Hi, I am not able for the mom. to test it, but to be sure that I understand y: As a precondition it is still needed to startup the monitor before I can use a client like a browser on Android ?

**Comment by guigrpa** [comment]
I'm not sure I understand you so I'll try to recap.

One of the ideas behind Storyboard was to be able to use a normal web application in a browser, jump to the DevTools and see not only your client logs (as in the console), but also related server logs. This works great in Chrome.

Now if you ask about other browsers, what you can do with **v1.1.0** (I just published it) is configure the WebSocket Client that is *included in Storyboard* so that it uploads the logs to the server, and connect to  the server from a Chrome browser, where you will be able to see the remote logs. I think this architecture not only solves your problems, but also opens the door to many new ideas: save all client logs in a database, analyse user actions, etc.

I'm closing this issue since I believe PR #9 covers the original post.

**Comment by Nic2012** [comment]
In a 1st mom. y comment and solution wasnt clear for me.
But nevertheless, thank y for y efforts.
